//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRA.DBQuizard
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewGuest
    {
        public int IDGuest { get; set; }
        public string Nickname { get; set; }
        public System.DateTime DateOfCreation { get; set; }
    }
}
