//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRA.DBQuizard
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserAcc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAcc()
        {
            this.Quiz = new HashSet<Quiz>();
        }
    
        public int IDUserAcc { get; set; }
        [Required(ErrorMessage = "Email je obvezan")] //erro poruka ako ga nema
        [Display(Name = "Email:")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Šifra je obvezna")] //erro poruka ako ga nema
        [Display(Name = "Šifra:")]
        public string Pass { get; set; }
        [Required(ErrorMessage = "Nadimak je obvezan")] //erro poruka ako ga nema
        [Display(Name = "Nadimak:")]
        public string Username { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz> Quiz { get; set; }
    }
}
